<script lang="ts">
	let { data } = $props();

	let qrDataUrl = $state<string>('');
	let error = $state('');
	let refreshing = $state(false);
	let isActive = $state<boolean>(false);

	$effect(() => {
		qrDataUrl = data.authorized ? String(data.qrDataUrl ?? '') : '';
		isActive = Boolean(data.isActive);
	});

	const refreshQr = async () => {
		if (!data.authorized) return;
		refreshing = true;
		try {
			const res = await fetch('/api/attendance/public/refresh', {
				method: 'POST',
				headers: { 'content-type': 'application/json' },
				body: JSON.stringify({ accessToken: data.accessToken })
			});
			const body = await res.json().catch(() => null);
			if (!res.ok) {
				error = body?.error ?? 'Could not refresh attendance QR.';
				return;
			}
			qrDataUrl = String(body?.qrDataUrl ?? '');
			isActive = Boolean(body?.isActive);
			error = '';
		} finally {
			refreshing = false;
		}
	};

	$effect(() => {
		if (!data.authorized) return;
		const timer = setInterval(() => {
			if (!isActive) {
				void refreshQr();
				return;
			}
			const now = new Date();
			if (now.getMinutes() === 0) void refreshQr();
		}, 30_000);
		return () => clearInterval(timer);
	});
</script>

<section class="mx-auto max-w-xl space-y-5 py-4">
	{#if !data.authorized}
		<div class="rounded-xl border border-slate-800 bg-slate-900 p-5 text-sm text-slate-300">
			<p class="font-semibold text-slate-100">Attendance display link required</p>
			<p class="mt-2">
				Open this page using the special link generated by a mentor after they scan your passport QR.
			</p>
		</div>
	{:else}
		<div class={`rounded-xl border p-5 text-center ${isActive ? 'border-sky-500 bg-slate-900' : 'border-red-500 bg-red-950/20'}`}>
			<p class="text-xs font-medium uppercase tracking-[0.18em] text-slate-500">Attendance QR</p>
			<h1 class="mt-1 text-2xl font-semibold">{data.attendee?.full_name || data.attendee?.email || 'Attendance'}</h1>
			<p class="mt-2 text-sm text-slate-400">
				{#if isActive}
					Active. Keep this open; scans now toggle attendance for the 4:30 AM - 4:29 AM day window.
				{:else}
					Inactive. Have a mentor scan this red QR once to activate attendance mode.
				{/if}
			</p>
			{#if qrDataUrl}
				<img
					src={qrDataUrl}
					alt="Attendance QR code"
					class={`mx-auto mt-4 w-72 max-w-full rounded-lg bg-white p-3 ${isActive ? 'border-2 border-sky-500' : 'border-2 border-red-500'}`}
				/>
			{/if}
			<div class="mt-4 flex justify-center">
				<button
					type="button"
					onclick={refreshQr}
					disabled={refreshing}
					class="rounded-md border border-slate-700 bg-slate-800 px-4 py-2 text-sm font-medium text-slate-200 hover:bg-slate-700 disabled:opacity-60"
				>
					{refreshing ? 'Refreshing…' : 'Refresh QR'}
				</button>
			</div>
			{#if error}<p class="mt-3 text-sm text-red-300">{error}</p>{/if}
		</div>
	{/if}
</section>
